# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

# Ignore all warnings from all pods
inhibit_all_warnings!

target 'Jigsaw' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Firebase framework
  pod 'Firebase/Database', '~> 8.9.0'
  pod 'Firebase/Auth', '~> 8.9.0'
  pod 'Firebase/Storage', '~> 8.9.0'
  pod 'Firebase/Firestore', '~> 8.9.1'
  pod 'Firebase/Functions', '~> 8.9.0'

  # Firebase UI for sign up/in
  # pod 'FirebaseUI', '~> 12.0.2'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Email'
  pod 'FirebaseUI/OAuth'  # Used for Sign in with Apple, Twitter, etc

  # Swift Codable
  # pod 'FirebaseFirestore'
  pod 'FirebaseFirestoreSwift', '~> 8.9.0-beta'

  # pod 'ResearchKit'

  # Messaging UI
  pod 'MessageKit'

  # Image lazy loading
  pod 'PINRemoteImage'

  # Image viewer for chatroom
  pod 'Agrume'

  # Profile forms
  pod 'Eureka'
  pod 'ViewRow'

  # ProgreeHUD
  pod 'ProgressHUD'

  # Game result showing in charts
  pod 'Charts'

  # Questionnaire YAML
  pod 'Yams'

  # Markdown to `NSAttributedString`
  pod 'Down'

  # Localization
  pod 'SwiftGen', '~> 6.0'

  # Profanity Filter
  pod 'AAProfanityFilter'

end

# Bump all Pod minimum target to iOS 14, to cope with Xcode 13
post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |bc|
      bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
  pi.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
    end
  end
end
