# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'Jigsaw' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

# Pods for Jigsaw
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'

# For Swift Codable
pod 'FirebaseFirestoreSwift'

# pod 'ResearchKit'

# Messaging UI
pod 'MessageKit'

# Image lazy loading
pod 'PINRemoteImage'

# Profile forms
pod 'Eureka'
pod 'ViewRow'

end
