# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jigsaw' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jigsaw
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/Storage'
pod 'ResearchKit'
end
